---
- name: Install and configure Vault
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: update_cache

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Download and install Vault
      get_url:
        url: "https://releases.hashicorp.com/vault/1.9.4/vault_1.9.4_linux_amd64.zip"
        dest: /tmp/vault.zip
      register: download_vault
      until: download_vault is succeeded

    - name: Unzip Vault
      unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin
        remote_src: yes
      when: download_vault is succeeded

    - name: Start Vault
      command: vault server -dev -dev-listen-address="0.0.0.0:8200"
      async: 300
      poll: 0
      ignore_errors: true
